version: '3.8'

services:
  backend:
    build: ../
    restart: always
    env_file:
      - ./.env
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - /etc/hosts:/etc/hosts:ro
